<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/17/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Activity implements JsonSerializable {
    /**
     * Unique identifier for the activity
     * @var string $uuid public property
     */
    public $uuid;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $uuid   Initialization value for the property $this->uuid
     */
    public function __construct()
    {
        if(1 == func_num_args())
        {
            $this->uuid = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['uuid'] = $this->uuid;

        return $json;
    }
}