<?php 
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/17/2016
 */

namespace UberAPILib\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Product implements JsonSerializable {
    /**
     * Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
     * @maps product_id
     * @var string $productId public property
     */
    public $productId;

    /**
     * Description of product.
     * @var string $description public property
     */
    public $description;

    /**
     * Display name of product.
     * @maps display_name
     * @var string $displayName public property
     */
    public $displayName;

    /**
     * Capacity of product. For example, 4 people.
     * @var string $capacity public property
     */
    public $capacity;

    /**
     * Image URL representing the product.
     * @var string $image public property
     */
    public $image;

    /**
     * Constructor to set initial or default values of member properties
     * @param   string            $productId      Initialization value for the property $this->productId   
     * @param   string            $description    Initialization value for the property $this->description 
     * @param   string            $displayName    Initialization value for the property $this->displayName 
     * @param   string            $capacity       Initialization value for the property $this->capacity    
     * @param   string            $image          Initialization value for the property $this->image       
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->productId    = func_get_arg(0);
            $this->description  = func_get_arg(1);
            $this->displayName  = func_get_arg(2);
            $this->capacity     = func_get_arg(3);
            $this->image        = func_get_arg(4);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['product_id']   = $this->productId;
        $json['description']  = $this->description;
        $json['display_name'] = $this->displayName;
        $json['capacity']     = $this->capacity;
        $json['image']        = $this->image;

        return $json;
    }
}