<?php
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 08/22/2014
 */

class HistoryModel {
    /**
     * History item id
     * @param string $uuid public property
     */
    protected $uuid;

    /**
     * Time when requested
     * @param int $request_time public property
     */
    protected $request_time;

    /**
     * The product that was used
     * @param string $product_id public property
     */
    protected $product_id;

    /**
     * Status of the product e.g., completed
     * @param string $status public property
     */
    protected $status;

    /**
     * Distance travelled
     * @param double $distance public property
     */
    protected $distance;

    /**
     * Time of starting the journey
     * @param int $start_time public property
     */
    protected $start_time;

    /**
     * Location of starting the journey
     * @param LocationModel $start_location public property
     */
    protected $start_location;

    /**
     * Time of journey end
     * @param int $end_time public property
     */
    protected $end_time;

    /**
     * Location where journey ended
     * @param LocationModel $end_location public property
     */
    protected $end_location;

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }
} 