<?php
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 08/22/2014
 */

class ProductModel {
    /**
     * Unique identifier representing a specific product for a given latitude & longitude. For example, uberX in San Francisco will have a different product_id than uberX in Los Angeles.
     * @param string $product_id public property
     */
    protected $product_id;

    /**
     * Description of product.
     * @param string $description public property
     */
    protected $description;

    /**
     * Display name of product.
     * @param string $display_name public property
     */
    protected $display_name;

    /**
     * Capacity of product. For example, 4 people.
     * @param int $capacity public property
     */
    protected $capacity;

    /**
     * Image URL representing the product.
     * @param string $image public property
     */
    protected $image;

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }
} 