<?php
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 08/22/2014
 */

class UserActivityModel {
    /**
     * Position in pagination.
     * @param int $offset public property
     */
    protected $offset;

    /**
     * Number of items to retrieve (100 max).
     * @param int $limit public property
     */
    protected $limit;

    /**
     * Total number of items available.
     * @param int $count public property
     */
    protected $count;

    /**
     * Information including the pickup location, dropoff location, request start time, request end time, and distance of requests (in miles), as well as the product type that was requested.
     * @param array $history public property
     */
    protected $history;

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }
} 