<?php
/*
 * UberAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 07/17/2016
 */

namespace UberAPILib;

use UberAPILib\Controllers;

/**
 * UberAPILib client class
 */
class UberAPIClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct($oAuthAccessToken = NULL)
    {
        Configuration::$oAuthAccessToken = $oAuthAccessToken ? $oAuthAccessToken : Configuration::$oAuthAccessToken;
    }
 
    /**
     * Singleton access to Products controller
     * @return Controllers\ProductsController The *Singleton* instance
     */
    public function getProducts()
    {
        return Controllers\ProductsController::getInstance();
    }
 
    /**
     * Singleton access to Estimates controller
     * @return Controllers\EstimatesController The *Singleton* instance
     */
    public function getEstimates()
    {
        return Controllers\EstimatesController::getInstance();
    }
 
    /**
     * Singleton access to User controller
     * @return Controllers\UserController The *Singleton* instance
     */
    public function getUser()
    {
        return Controllers\UserController::getInstance();
    }
}